
[[item]]
file = "/var/log/antikoerper/temp.zone1"
regex = "(?P<ts>\\d+)\\s(?P<temp>\\d+)"
alias = "tempmain"

[[item]]
file = "/var/log/antikoerper/os.load"
regex = "(?P<ts>\\d+)\\s(?P<load1m>\\d+\\.\\d\\d)\\s(?P<load5m>\\d+\\.\\d\\d)\\s(?P<load15m>\\d+\\.\\d\\d)\\s"
alias = "load"

